pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=dependabot[bot]
      - label=auto-merge
    actions:
      merge:
        method: merge
        commit_message: title+body
      - delete_head_branch: {}